AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AdopEIP:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/adop-infra/component-pre-eip.yaml
      TimeoutInMinutes: '60'
  AdopFlowlogs:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/adop-infra/component-role-flowLogs.yaml
      TimeoutInMinutes: '60'
  AdopVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/adop-infra/component-vpc.yaml
      Parameters:
        FlowLogARN: !GetAtt AdopFlowlogs.Outputs.ARNID
      TimeoutInMinutes: '60'
    DependsOn: AdopFlowlogs
  AdopPublicNetwork:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/adop-infra/component-public-network.yaml
      Parameters:
        VpcAvailabilityZones: 'ap-southeast-1a,ap-southeast-1b'
        BaseVpcId: !GetAtt AdopVPC.Outputs.BaseVpcId
        VpcInternetGatewayId: !GetAtt AdopVPC.Outputs.InternetGatewayId
        NATGatewayEIPId1: !GetAtt AdopEIP.Outputs.NatGatewayEIP1
        NATGatewayEIPId2: !GetAtt AdopEIP.Outputs.NatGatewayEIP2
      TimeoutInMinutes: '60'
    DependsOn: AdopVPC
  AdopPrivateNetwork:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/adop-infra/component-private-network.yaml
      Parameters:
        AvailabilityZone: 'ap-southeast-1a'
        NATGatewayId: !GetAtt AdopPublicNetwork.Outputs.NatGatewayAz1ID
        BaseVpcId: !GetAtt AdopVPC.Outputs.BaseVpcId
      TimeoutInMinutes: '60'
    DependsOn: AdopPublicNetwork
  AdopService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/adop-infra/service-adop-c.yaml
      Parameters:
        AdopUsername: 'adop'
        AdopUserPassword: 'adop1234'
        SecretS3BucketStore: 'adop-data'
        VpcID: !GetAtt AdopVPC.Outputs.BaseVpcId
        VPCSubnet: !GetAtt AdopPrivateNetwork.Outputs.PrivateSubnetId
        KeyName: 'gavin'
        NtpRegion: 'sg'
      TimeoutInMinutes: '60'
    DependsOn: AdopPublicNetwork
